title: Página de Hugo
description: Página creada con la plantila Jekyll
theme: just-the-docs

url: https://hugolugilde.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs
    hide_icon: false 
    opens_in_new_tab: true
