title: Sindicato de Estudiantes
description: Página con información sobre los derechos de los estudiantes
theme: just-the-docs

url: https://hugolugilde.github.io

search_enabled: false

favicon_ico: https://github.com/hugolugilde/hugolugilde.github.io/blob/main/sindicato.ico

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_external_links:
  - title: Sindicato de estudiantes
    url: https://www.sindicatodeestudiantes.net/
    hide_icon: false 
    opens_in_new_tab: true
