title: Sindicato de Estudiantes
description: Página con información sobre los derechos de los estudiantes
theme: just-the-docs

url: https://hugolugilde.github.io

search_enabled: false

nav_enabled: true

favicon_ico: "/sindicato.ico"

nav_external_links:
  - title: Sindicato de estudiantes
    url: https://www.sindicatodeestudiantes.net/
    hide_icon: false 
    opens_in_new_tab: true
